#!/bin/bash

# Generate environment variables for client-side use
# This script runs at build time to create assets/js/env.js
# 
# SECURITY: Only non-sensitive values are exposed to the client:
# - META_PIXEL_ID: Public Facebook Pixel ID (safe to expose)
# - TURNSTILE_SITE_KEY: Public Cloudflare Turnstile site key (safe to expose)
# - FBCAPTURE_DEBUG: Debug flag (safe to expose)
#
# Sensitive secrets (TURNSTILE_SECRET_KEY, MAKE_WEBHOOK_*) are NOT exposed

set -e

# Create the assets/js directory if it doesn't exist
mkdir -p assets/js

# Create the env.js file with environment variables
cat > assets/js/env.js << EOF
// Environment variables generated at build time
// DO NOT EDIT THIS FILE - it is automatically generated

window.ENV = {
  META_PIXEL_ID: "${META_PIXEL_ID:-}",
  TURNSTILE_SITE_KEY: "${TURNSTILE_SITE_KEY:-}",
  FBCAPTURE_DEBUG: "${FBCAPTURE_DEBUG:-false}"
};
EOF

echo "Generated assets/js/env.js with environment variables"
